var _tmr=_tmr||[];
(function(){function Q(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function ka(a){return"[object Array]"===Object.prototype.toString.call(a)}function t(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function C(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Y(a,b){for(var c=0;c<b.length;c++)if(b[c]==a)return!0;return!1}function N(a,b){var c,d;if(!a||
!Q(a))return"";var e=[];if(ka(a)){c=0;for(d=a.length;c<d;c++)wa(e,null,a[c],b);c="[";d="]"}else{for(c in a)a.hasOwnProperty(c)&&wa(e,c,a[c],b);c="{";d="}"}return!e.length?"":c+e.join(",")+d}function wa(a,b,c,d){var e=typeof c;if("string"===e)c='"'+c.replace(/[\"\']/g,"\\$&")+'"';else if(!("number"===e||"boolean"===e))if(c=d?"":N(c),!c.length)return;a.push((null===b?"":'"'+b+'":')+c)}function la(){var a=arguments,b=a[0]||{},c=!1,d=1,e=a.length,v,l,g,f,k;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(Q(b)||
(b={});d<e;d++)if(null!=(v=a[d]))for(l in v)g=b[l],f=v[l],b!==f&&(c&&f&&(Q(f)||(k=ka(f)))?(k?(k=!1,g=g&&ka(g)?g:[]):g=g&&Q(g)?g:{},b[l]=la(c,g,f)):void 0!==f&&(b[l]=f));return b}function xa(a){var b="";try{var c=new Uint8Array(a);f.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(e){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function p(){return(new Date).getTime()}function n(a,b){var c={data:b,raw:a,url:"https://top-fwz1.mail.ru"+a},
d;"function"!==typeof s.sendBeacon?d=!1:(c.dataSplitter=";",d=Z(c.data,c.dataSplitter),d=!0===s.sendBeacon(c.url,d));d||(void 0===b?(c.dataSplitter=";",c.open=$a,c.connect=ab,c.startListen=bb,c.stopListen=cb,c.open(c),c.connect(c)):("function"===typeof f.XMLHttpRequest?(c.dataSplitter=";",c.open=db,c.connect=eb,c.startListen=fb,c.stopListen=gb,c.open(c),c.connect(c),d=!0):d=!1,d||hb(c)))}function hb(a){var b=g.createElement("iframe"),c=g.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");
c.appendChild(b);g.body.appendChild(c);try{var d=b.contentWindow.document,e=d.createElement("div"),v;for(v in a.data)if(a.data.hasOwnProperty(v)){var l=a.data[v],f=typeof l;if("string"===f||"number"===f){var h=d.createElement("input");h.setAttribute("type","hidden");h.setAttribute("name",v);h.value=l;e.appendChild(h)}}var p=d.createElement("form");p.setAttribute("action",a.url);p.setAttribute("method",ya);p.setAttribute("enctype",za);p.appendChild(e);var m=d.createElement("div");m.appendChild(p);
d.body.appendChild(m);var q=function(){try{C(b,"load",q),g.body.removeChild(c)}catch(a){k&&console.warn("[TopMailRu] Error#1.2",a)}};t(b,"load",q);p.submit()}catch(r){k&&console.warn("[TopMailRu] Error#1.3",r)}}function db(a){a._connection=new f.XMLHttpRequest}function eb(a){a._connection.open(ya,a.url);a._connection.setRequestHeader("Content-Type",za);a._connection.send(Z(a.data,a.dataSplitter))}function fb(a){t(a._connection,"load",a._onload);t(a._connection,"error",a._onerror)}function gb(a){C(a._connection,
"load",a._onload);C(a._connection,"error",a._onerror)}function $a(a){a._connection=new Image}function ab(a){a._connection.src=a.url+Z(a.data,a.dataSplitter)}function bb(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function cb(a){a._connection.onload=null;a._connection.onerror=null}function Z(a,b){var c=b||";",d="",e;for(e in a)if(a.hasOwnProperty(e)){var g=a[e],l=typeof g;if("string"===l||"number"===l)d+=c+escape(e)+"="+escape(g)}return d}function $(a){return(a=g.cookie.match(RegExp("(?:^|; )"+
a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function F(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var e in c)if((b=c[e])||0===b)a+="; "+e,!0!==b&&(a+="="+b);g.cookie=a}function ib(){var a="tmr"+(""+Math.random()).slice(2);try{return z=f.localStorage||null,z.setItem(a,a),z.removeItem(a),!0}catch(b){return z=
null,k&&console.warn("[TopMailRu] Error#1.4",b),!1}}function jb(){if(!aa)return null;for(var a=x.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var e=1;e<=c;e++)b=a[e]+"."+b;var e=""+p(),g={domain:b,path:"/",expires:3E5};try{F("tmr_tcdhn",e,g);var l=$("tmr_tcdhn"),g=g||{};g.expires=-1;F("tmr_tcdhn","",g);if(l===e)return b}catch(f){k&&console.warn("[TopMailRu] Error#1.8",f)}}return null}function ba(a,b){aa&&F(a,b,Aa);if(ma)try{z.setItem(a,b)}catch(c){k&&console.warn("[TopMailRu] Error#1.6",
c)}}function na(a){var b;if(!(b=aa?$(a):null)){var c;if(ma)a:{try{c=z.getItem(a);break a}catch(d){k&&console.warn("[TopMailRu] Error#1.5",d)}c=null}else c=null;b=c}return b}function Ba(a){var b=";e="+escape("detect");n(w(a,"/tracker",!1,!1)+b)}function Ca(a,b){if(a.length){var c=N(b.ecom_data);4096<c.length||(b.ecom_data._m=b.ecom_method,b.ecom_data._t=b.ecom_type,c=N(b.ecom_data),delete b.ecom_data._m,delete b.ecom_data._t,n(w({id:a[0]},"/datalayer",!1,!1)+(";ids="+escape(a.join()))+(";e="+escape(c))))}}
function kb(){var a=$(Da);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=p()-b;return 0>b||b>Ea?null:{id:a[0],version:a[1]}}function h(){}function R(a){a&&"object"===typeof a&&(!A&&"id"in a)&&(A=a.id)}function lb(a){return(a=!D?void 0:D[a])&&oa?a-oa:void 0}function Fa(){if(D){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=!D?void 0:D[b[c]];if(0<d&&(d<a||
0==a))a=d}return a?a:void 0}}function S(a){return a&&"object"===typeof a&&("id"in a&&a.id||A)}function w(a,b,c,d){ba(pa,++J);var e="id"in a?a.id:A,v="url"in a?a.url:x.href,l="referrer"in a?a.referrer:g.referrer,h="title"in a?a.title:g.title,m;m=qa;null===m&&(m=mb());m=null!==m?m?1:0:null;var r="userid"in a?a.userid:B||0===B?B:void 0,t=E?E:void 0,q;q=[];A&&e!==A&&q.push("sec");"dataLayer"in f&&q.push("dl");K&&q.push(["ecom"].concat(K).join("-"));q=q.join(",");var n=f.screen,u,L=(new Date).getTimezoneOffset();
u="";if(f.Intl)try{u=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(nb){k&&console.warn("[TopMailRu] Error#1.1",nb)}u=L+"/"+u;L=Ga;L=null!==L?L:kb();a.start=Fa();b=b+"?js=13"+(e?";id="+escape(e):"")+(v?";u="+escape(v):"")+(l?";r="+escape(l):"")+(a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==r?";userid="+escape(r):"")+(void 0!==t?";uparams="+escape(N(t,!1)):"")+(d&&h?
";title="+encodeURIComponent(h):"")+(n?";s="+n.width+"*"+n.height:"")+";vp=";e=d=0;g.documentElement&&(g.documentElement.clientWidth||g.documentElement.clientHeight)?(d=g.documentElement.clientWidth,e=g.documentElement.clientHeight):"number"==typeof f.innerWidth&&(d=f.innerWidth,e=f.innerHeight);b=b+(""+d+"*"+e)+";touch="+ob+";hds="+pb+";frame="+qb+";flash=";if(null===T)if(T="",s.plugins&&s.plugins["Shockwave Flash"])T=s.plugins["Shockwave Flash"].description.split(" ")[2];else if(f.ActiveXObject)try{var y=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),y=y.GetVariable("$version"),y=y.split(" ")[1].split(",");T=y[0]+"."+y[1]}catch(rb){k&&console.warn("[TopMailRu] Error#1.12",rb)}y=b+T+";sid="+Ha+";ver="+Ia+";tz="+encodeURIComponent(u);if(c){if(!D||!ra)c="";else{c=[];c.push(ra.type);c.push(ra.redirectCount);c.push(oa);for(b=0;b<Ja.length;b++)c.push(lb(Ja[b]));c=c.join("/")}c=";nt="+c}else c="";c=y+c+("device"in a?";device="+escape(a.device):"")+";ni=";if(!s||!s.connection)y="";else{y=s.connection;
b=[];for(e=0;e<Ka.length;e++){d=y[Ka[e]];if(void 0!==d)switch(d){case !0:d=1;break;case !1:d=0;break;default:d=(""+d).replace(/\//g,"_")}b.push(d)}y=b.join("/")}return c+y+("params"in a?";params="+escape(N(a.params,!1)):"")+(null!==m?";detect="+m:"")+(aa||ma?";lvid="+escape([U,p(),J,M].join(":")):"")+(q?";opts="+escape(q):"")+(L?";flocid="+escape(L.id)+";flocv="+escape(L.version):"")+("version"in a?";appver="+escape(a.version):"")+(O.support?";visible="+O.getValue():"")+";_="+Math.random()}function La(a){a=
";e="+escape("PVT/"+a);for(var b=0;b<r.length;b++)n(w(r[b],"/tracker",!1,!0)+a)}function sb(){qa=!0;Ma(1);if(!Na&&!V){V=!0;for(var a=0;a<r.length;a++)Ba(r[a])}}function tb(){Ma(0);qa=!1}function mb(){var a=$(Oa);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=p()-b;if(0>b||b>Pa)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function Ma(a){var b=p();a=[a,b].join("|");F(Oa,a,{path:"/",expires:Pa})}function ca(){g.addEventListener?(C(g,"DOMContentLoaded",ca),_tmr.onready()):
g.attachEvent&&"complete"===g.readyState&&(C(g,"readystatechange",ca),_tmr.onready())}function Qa(){C(f,"load",Qa);_tmr.onready();_tmr.onload()}function da(){C(f,"unload",da);C(f,"beforeunload",da);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var f=window,s=navigator,g=document,x=location,W="string"===typeof x.hostname?x.hostname:"",ea=-1!=W.search(/(^|\.)odnoklassniki\.ru$/)||-1!=W.search(/(^|\.)ok\.ru$/),fa=-1!=W.search(/(^|\.)vk\.com$/),ub=-1!=W.search(/(^|\.)lamoda\.ru$/),
vb=-1!=W.search(/(^|\.)kommersant\.ru$/),wb="string"===typeof x.search&&-1!=x.search.search(/[?&]rb_clickid=/),k="string"===typeof x.search&&-1!=x.search.search(/[?&]tmr_debug=1(?:&|$)/),Ra=ea||fa||ub||vb,xb=!wb,yb=ea||fa,zb=ea||fa,Sa=ea||fa,Na=!1,ya="POST",za="application/x-www-form-urlencoded",aa=!(0===x.hostname.search(/^(\d+.)+\d+$/g)||-1!==x.hostname.search(/:/g)),z=null,ma=ib(),Aa={domain:jb(),path:"/",expires:287712E5};(function(){var a;if(a=g.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)",
"g"))){for(var b=[],c,d=0,e=a.length;d<e;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){b=0;for(d=a.length;b<d;b++)e=a[b][0],c=Aa||{},c.expires=-1,F(e,"",c)}})();var V=!1,qa=null,Pa=864E5,Oa="tmr_detect",Ab=function(){function a(a,c){var d=g.createElement("div");d.setAttribute("class",String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,109,109,98,108,111,99,107,32,98,45,98,97,110,110,101,114,32,98,45,
109,101,100,105,97,45,98,97,110,110,101,114,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,109,101,100,105,117,109,95,114,101,99,116,97,110,103,108,101,95,51,48,48,95,50,53,48,32,112,117,98,95,55,50,56,120,57,48,32,108,101,97,100,101,114,98,111,97,114,100,95,55,50,56,95,57,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,95,54,48,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,120,54,48,48,32,116,101,120,116,
45,97,100,32,116,101,120,116,65,100,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,97,100,95,116,101,120,116,32,97,100,95,116,101,120,116,32,98,97,110,110,101,114,95,116,101,120,116,32,116,101,120,116,45,98,97,110,110,101,114,32,98,45,114,98,32,114,98,45,115,108,111,116,32,98,45,112,114,111,109,111,45,97,100,32,105,45,98,114,97,110,100,105,110,103,32,98,114,97,110,100,105,110,103,45,112,32,114,98,
45,118,105,100,101,111,45,119,105,100,103,101,116,32,98,45,109,105,109,105,99,45,97,100,118,32,112,109,45,116,111,111,108,98,97,114,95,95,98,97,110,110,101,114,32,114,98,95,98,111,100,121,32,115,116,105,99,107,121,45,115,112,114,105,110,103,115,32,97,100,118,95,115,108,111,116,95,49,32,98,97,110,110,101,114,95,50,52,48,32,98,108,111,99,107,95,115,104,97,114,101,32,97,99,116,105,111,110,45,45,115,104,97,114,101,32,115,104,97,114,101,108,105,115,116,32,106,115,45,98,97,110,110,101,114,32,100,105,114,
101,99,116,32,112,99,45,109,105,109,105,99,32,116,103,98,45,98,97,110,110,101,114,32,121,97,100,105,114,101,99,116,32,106,115,45,112,114,111,109,111,45,112,111,112,117,112,32,109,45,115,117,98,115,99,114,105,112,116,105,111,110,32,112,45,116,97,114,103,101,116,32,112,45,100,105,114,101,99,116,104,97,99,107,32,114,98,45,102,108,111,97,116,105,110,103,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107));d.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");
d.setAttribute("id","trg-b-banners-1");d.setAttribute("data-view","SlotView.mimic");this.bait=g.body.appendChild(d);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=a||null;this.fnNegative=c||null;var e=this;setTimeout(function(){e._checkBait.call(e)},1)}a.prototype._checkBait=function(){if(V)this._stop();else{var a=!1;null!==g.body.getAttribute("abp")||null===
this.bait.offsetParent||0==this.bait.offsetHeight||0==this.bait.offsetLeft||0==this.bait.offsetTop||0==this.bait.offsetWidth||0==this.bait.clientHeight||0==this.bait.clientWidth?a=!0:void 0!==f.getComputedStyle&&(a=f.getComputedStyle(this.bait,null),a="none"==a.getPropertyValue("display")||"hidden"==a.getPropertyValue("visibility"));(!0===a||10<=++this.loopNumber)&&this._stop();var c;if(a&&this.fnPositive)try{c=this.fnPositive,c()}catch(d){k&&console.warn("[TopMailRu] Error#1.9",d)}else if(!a&&10>
this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}else try{c=this.fnNegative,c()}catch(v){k&&console.warn("[TopMailRu] Error#1.10",v)}}};a.prototype._stop=function(){try{g.body.removeChild(this.bait)}catch(a){k&&console.warn("[TopMailRu] Error#1.11",a)}};return function(b,c){new a(b,c)}}(),K=null,Ta=!1,sa=[],Bb=[36383,2540645,3171181,3074137,2057653],Cb=[],Ua;(function(){function a(a,b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,
c,d){for(var e={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},g=0,l=b.length;g<l;g++){var f=n[b[g]];if(f){a(e.ecom_method,[b[g]]);for(var h=0,v=f.length;h<v;h++)for(var k=0,m=d.length;k<m;k++){var p=f[h][d[k]];if(p)for(var q=0,r=c.length;q<r;q++)if(-1!==f[h].type.indexOf(c[q])){a(e.ecom_type,[c[q]]);a(e.ecom_data.events,p);break}}}}return e}function c(a,b,c){if(!a||!c||!(b in n))return null;for(var d,e=0,g=n[b].length;e<g;e++)if(d=n[b][e],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type,
ecom_data:{}};return null}function d(a){for(var d=[],e,f,n=0,x=a.length;n<x;n++)if(f=a[n]){e=null;try{if(f.ecommerce){var w;a:{var s=f,u=void 0,B=void 0,H=void 0;for(H in s.ecommerce)if(s.ecommerce.hasOwnProperty(H)&&(u=c(H,l,p))){if(s.event&&(B=c(s.event,l,r)))for(var H=0,C=u.ecom_type.length;H<C;H++)-1===B.ecom_type.indexOf(u.ecom_type[H])&&(u.ecom_type.splice(H,1),C--,H--);u.ecom_data=s.ecommerce;w=u;break a}w=null}var A;if(!(A=w)){var D=f.event,E=c(D,l,r);E&&(E.ecom_data[D]=f.ecommerce);A=E}e=
A}else if("event"===f[0]){var G=f[1],I=f[2],F=c(G,h,q);F&&(F.ecom_data[G]=I);e=F}else if(f.event===g)a:{for(var z=b([l],[m],[t]),s=0,J=z.ecom_data.events.length;s<J;s++)if(!f.hasOwnProperty(z.ecom_data.events[s])){e=null;break a}delete z.ecom_data.events;z.ecom_data[g]=f;e=z}}catch(M){k&&console.warn("[TopMailRu] Error#1.23",M),e=null}e&&(d.push(e),sa.push(e))}if(d.length){a=0;for(e=d.length;a<e;a++)Ca(ga,d[a]);K||(K=[0,0]);K[0]+=d.length;e=a=0;for(n=d.length;e<n;e++)a+=N(d[e].ecom_data).length;K[1]+=
a}}function e(a){if((a=f[a])&&"function"===typeof a.push){d(a);var b=a.push;a.push=function(){var a=b.apply(this,arguments);d([].slice.call(arguments,0));return a}}}var g="ecommerce",l="push",h="gtag",m="gse",p="inner",r="outer",q="external",t="required",n={};n[h]=[{type:["gee"],external:["set_checkout_option","checkout_progress"]},{type:["ga4"],external:["select_item","select_promotion","add_shipping_info","view_cart"]},{type:["gee","ga4"],external:"add_payment_info generate_lead view_promotion add_to_cart add_to_wishlist begin_checkout purchase refund remove_from_cart view_item view_item_list".split(" ")}];
n[l]=[{type:[m],required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([h],["ga4"],[q]).ecom_data.events},{type:["gee"],inner:"click checkout refund promoView promoClick checkout_option".split(" "),outer:["productDetail","addToCart","removeFromCart","transactionPush"]},{type:["ym","gee"],inner:["detail","add","remove","purchase"]}];Ua=function(){e("dataLayer");Ta=!0}})();var Ea=864E5,Da="tmr_floc",Ga=null;(function(a){try{document.interestCohort&&"function"===typeof document.interestCohort&&
document.interestCohort().then(function(a){Ga={id:a.id,version:a.version};a=[a.id,a.version];var b=p();a=a.concat(b).join("|");F(Da,a,{path:"/",expires:Ea})},function(){})}catch(b){}})();var O={support:!1},O=function(){function a(){d(h)}function b(){d(h,r)}function c(){return l?!g[l]:null}function d(a,b){var d=p(),g="undefined"===typeof b?c():b;if(null===q[a])q[a]={ts:d,state:g,total:0};else{var f=q[a];if(f.state!==g){var l=d-f.ts,h=f.state;f.ts=d;f.state=g;l<e||(h===m?(f.total+=l,s&&s(d,l)):h===
n&&u&&u(d,l))}}}var e=5,h="auto",l=null,k=null,m=!0,n=!1,r=null;"hidden"in g?(l="hidden",k="visibilitychange"):"mozHidden"in g?(l="mozHidden",k="mozvisibilitychange"):"webkitHidden"in g?(l="webkitHidden",k="webkitvisibilitychange"):"msHidden"in g&&(l="msHidden",k="msvisibilitychange");var q={};q[h]=null;var s=q.user=null,u=null;return{support:!!l,auto:function(c,d){s=c||null;u=d||null;l&&(a(),t(g,k,a));t(f,"beforeunload",b);t(f,"unload",b)},set:function(a){d("user",!!a)},getLog:function(){var a=p(),
b={},c,d;for(d in q)c=q[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:c}}();O.auto();var Ia="60.3.0",ta=0,ha=0,Ha=xa(16),B=null,E=null,ia=0,pa="tmr_reqNum",J=na(pa),J=null===J?0:parseInt(J,10);ba(pa,J);var M=na("tmr_lvid"),U=na("tmr_lvidTS");if(null===M||-1===M.search(/^[0-9a-fA-F]+$/))M=xa(32);ba("tmr_lvid",M);if(null===U||-1===U.search(/^\d+$/))U=""+p();ba("tmr_lvidTS",U);var A=0,r=[],ua=[],ja=[],ga=[],ob="ontouchstart"in f||1<(s.maxTouchPoints||s.msMaxTouchPoints)?"1":"0",pb=
f.devicePixelRatio||0,qb=f.top===f?0:1,T=null,Va=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},D=Va.timing||{},ra=Va.navigation||{},Ja="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),oa=!D?void 0:D.navigationStart,
Ka="downlink downlinkMax effectiveType rtt saveData type".split(" "),G,va;G=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||A,e=c.title||null,g,f=va(b,{params:c.required,fn:c.fn});if(f.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<f.missed.length&&f.missed.slice(0,-1).join(", ")+" and "||"")+f.missed.slice(-1)+" in "+a);else{var h=va(b,{params:c.optional,fn:c.fn});g=[].concat(f.values).concat(h.values);f=[].concat(f.missed).concat(h.missed);
c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?g.push("value: "+b):f.push("value"));c=g.length?"{ "+g.join(", ")+" }":"";g=f.length?"("+(1<f.length?f.slice(0,-1).join(", ")+" and "+f.slice(-1)+" are":f.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+c+" "+g):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};va=function(a,b){var c=[],d=[],e,f,g;if(b.params)for(e in b.params)if(b.params.hasOwnProperty(e)&&
!1!==b.params[e])if(f=e in a&&a[e],!0!==b.params[e]&&(f=f||b.params[e]),f)try{g=b.fn?b.fn:null,c.push(e+': "'+(g?g(e,f):f)+'"')}catch(h){console.warn("[TopMailRu] Error#1.16",h)}else d&&d.push(e);return{values:c,missed:d}};h.prototype.callbackOnReady=function(a){k&&G("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&a.callback.call(a.context||null)};h.prototype.pageView=function(a){R(a);if(a&&("object"===typeof a&&a.id)&&(5>ua.length&&!Y(a.id,ua)&&(ua.push(a.id),
!1!==a.beat&&ja.push(a.id),r.push(a),V&&Ba(a)),5>ga.length&&!Y(a.id,ga)&&(!0===a.ecom||!1!==a.ecom&&(Y(a.id,Bb)||!Y(a.id,Cb))))){ga.push(a.id);var b=[a.id];if(Ta)for(var c=0,d=sa.length;c<d;c++)Ca(b,sa[c])}k&&G("pageView",a,{title:"Page view",optional:{url:x.href}});S(a)&&(n(w(a,"/counter",!1,!0)),ha=p())};h.prototype.reachGoal=function(a){R(a);k&&G("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(S(a)&&"goal"in a&&a.goal){var b="";"value"in a&&a.value&&(b=parseInt(a.value)||"");
n(w(a,"/tracker",!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};h.prototype.itemView=function(a){k&&G("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(S(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0;(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||A)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();b="IV:"+e+"/"+(""+b).replace(/;/g," ")+
";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");n(w(a,"/tracker",!1,!1)+(";e="+escape(b)))}};h.prototype.sendEvent=function(a){R(a);k&&G("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substr(0,300).replace(/;/g," ")}});if(S(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substr(0,300),c=(""+a.action).substr(0,300),d="";"label"in a&&a.label&&(d=(""+a.label).substr(0,300));var e="";
"value"in a&&a.value&&(e=parseInt(a.value)||"");b="CE:"+e+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");n(w(a,"/tracker",!1,!1)+(";e="+escape(b)))}};h.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?k&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(B=a,k&&console.info("[TopMailRu]: Global user ID = "+B))}};h.prototype.getUserID=function(){return B||0===
B?B:void 0};h.prototype.deleteUserID=function(){B=null;k&&console.info("[TopMailRu]: Reset global user ID to null")};h.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(Q(a)){try{E=la(!0,{},a)}catch(b){k&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");return}k&&console.info("[TopMailRu]: Global user params = "+N(E,!1))}else k&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};h.prototype.getUserParams=
function(){var a=E?E:void 0;return a?la(!0,{},a):void 0};h.prototype.deleteUserParams=function(){E=null;k&&console.info("[TopMailRu]: Reset global user params to null")};h.prototype.getClientID=function(){var a=M;return a||0===a?a:void 0};h.prototype._MT_event=function(a,b,c){R(a);k&&G(b,a,{title:c});S(a)&&n(w(a,"/tracker",!1,!0)+(";e="+escape("MT:/"+b)))};h.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};h.prototype.processEvent=function(a,b){if(a&&"object"===
typeof a)if("type"in a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();
break;case "miniAppEvent":this.miniAppEvent(a)}}else k&&console.warn("[TopMailRu] Error#1.19","Unspecified type of push event");else k&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};h.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var Wa=!1;h.prototype.onready=function(){Wa||(Wa=!0,!Na&&!V&&Ab(sb,tb),Ua())};var Xa=!1;h.prototype.onload=function(){if(!Xa){Xa=!0;ia=p();if(!zb&&0<r.length){for(var a=";e="+escape("RT/load")+";et="+ia,
b=0;b<r.length;b++)n(w(r[b],"/tracker",!0,!1)+a);ha=ia}xb||setTimeout(function(){La(2)},2E3);yb||setTimeout(function(){La(15)},15E3)}};h.prototype.beat=function(){if(!Ra&&ta){var a=p();if(!(12E4<a-ta)){if(12E4<a-ha)for(var b=";e="+escape("RT/resend")+";et="+ia,c=0;c<r.length;c++)!1!==r[c].beat&&n(w(r[c],"/tracker",!1,!0)+b);else 0<ja.length&&n("/tracker?"+Z({js:"13",id:ja[0],e:"RT/beat",sid:Ha,ids:ja.join(),ver:Ia,_:Math.random()},";"));ha=a}}};var Ya=!1;h.prototype.unload=function(){if(!Ya&&(Ya=
!0,!Sa)){var a;a=(a=Fa())?p()-a:void 0;a=";e="+escape("RT/unload")+";et="+p()+(a?";pvt="+escape(a):"");if(O.support){var b=O.getLog();a+=";vtauto="+b.auto}for(b=0;b<r.length;b++)n(w(r[b],"/tracker",!1,!1)+a)}};h.prototype.activity=function(a){ta=p()};var P=_tmr;_tmr=new h;for(var m=0,X=P.length,I;m<X;m++)(I=P[m])&&"object"===typeof I&&R(I);m=0;for(X=P.length;m<X;m++)I=P[m],_tmr.processEvent(I,1);m=0;for(X=P.length;m<X;m++)I=P[m],_tmr.processEvent(I,-1);if("complete"===g.readyState||"loading"!==g.readyState&&
!g.documentElement.doScroll)_tmr.onready();else g.addEventListener?t(g,"DOMContentLoaded",ca):g.attachEvent&&t(g,"readystatechange",ca);if("complete"===g.readyState)_tmr.onload();else t(f,"load",Qa);Sa||(t(f,"unload",da),t(f,"beforeunload",da));if(!Ra){setInterval(function(){_tmr.beat()},6E4);try{for(var Za="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),Db=function(a){t(g,a,function(){_tmr.activity(a)})},m=0;m<Za.length;m++)Db(Za[m]);t(f,"scroll",function(){_tmr.activity("scallback")})}catch(Eb){k&&
console.warn("[TopMailRu] Error#1.20",Eb)}}}})();
